### ISSUE TITLE
Cloning 

### ISSUE THREAD

**Issue by ZSN98** [jaabell/gmsh2opensees#2]
I am trying to clone "git clone git@github.com:jaabell/gmsh2opensees.git" as you described,  but I keep getting permission denied.

**Comment by jaabell** [comment]
Hi, clone with HTTPS instead.

`git clone https://github.com/jaabell/gmsh2opensees.git`

I'm going to fix this instruction in the readme because regular users don't have write access to the repo, hence should clone using https and not git directly. 

Thanks!
